services:
  postgres-server:
    image: postgres:16.3-alpine
    container_name: chatgpt-postgres
    environment:
      - POSTGRES_USER=agentic
      - POSTGRES_PASSWORD=workflow
      - PGDATA=/pgdata
      - POSTGRES_DB=chatgptui
    ports:
      - 5432:5432
    volumes:
      - proxy-postgres-data:/pgdata
    networks:
      - chatgpt_ui_network
    restart: always


  client:
    image: agenticworkflow/chatgpt-ui:v240924
    environment:
      - SERVER_DOMAIN=http://backend-web-server
      - DEFAULT_LOCALE=en
#      - NUXT_PUBLIC_APP_NAME='ChatGPT UI' # The name of the application
#      - NUXT_PUBLIC_TYPEWRITER=true # Whether to enable the typewriter effect, default false
#      - NUXT_PUBLIC_TYPEWRITER_DELAY=50 # The delay time of the typewriter effect, default 50ms
    depends_on:
      - backend-web-server
    ports:
      - '${CLIENT_PORT:-80}:80'
    networks:
      - chatgpt_ui_network
    restart: always


  backend-wsgi-server:
    image: agenticworkflow/chatgpt-wsgi-server:v240924
    env_file: .env
    environment:
      - DEBUG=${DEBUG:-True} # Whether to enable debug mode, default False
      - APP_DOMAIN=${APP_DOMAIN:-localhost:9000}
      - SERVER_WORKERS=3 # The number of worker processes for handling requests.
      - WORKER_TIMEOUT=180 # Workers silent for more than this many seconds are killed and restarted. default 180s
      - DB_URL=postgres://agentic:workflow@postgres-server/chatgptui
      - DJANGO_SUPERUSER_USERNAME=admin # default superuser name
      - DJANGO_SUPERUSER_PASSWORD=password # default superuser password
      - DJANGO_SUPERUSER_EMAIL=admin@example.com # default superuser email
      - ACCOUNT_EMAIL_VERIFICATION=${ACCOUNT_EMAIL_VERIFICATION:-none} # Determines the e-mail verification method during signup – choose one of "none", "optional", or "mandatory". Default is "optional". If you don't need to verify the email, you can set it to "none".
      # If you want to use the email verification function, you need to configure the following parameters
#      - EMAIL_HOST=SMTP server address
#      - EMAIL_PORT=SMTP server port
#      - EMAIL_HOST_USER=
#      - EMAIL_HOST_PASSWORD=
#      - EMAIL_USE_TLS=True
#      - EMAIL_FROM=no-reply@example.com  #Default sender email address
    volumes:
      - ./datasets:/app/datasets
    ports:
      - '${WSGI_PORT:-8000}:8000'
    depends_on:
      - postgres-server
    networks:
      - chatgpt_ui_network
    restart: always


  backend-web-server:
    image: agenticworkflow/chatgpt-web-server:v240924
    environment:
      - BACKEND_URL=http://backend-wsgi-server:8000
    ports:
      - '${SERVER_PORT:-9000}:80'
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network
    restart: always


  jupyter:
    image: agenticworkflow/chatgpt-wsgi-server:v240924
    entrypoint:
      - jupyter
      - lab
      - --ip='0.0.0.0'
      - --allow-root
      - --NotebookApp.token=agenticworkflow
    env_file: .env
    ports:
      - '8888:8888'
    volumes:
      - ./datasets:/app/datasets
    depends_on:
      - backend-wsgi-server
    networks:
      - chatgpt_ui_network
    restart: always


volumes:
  proxy-postgres-data:

networks:
  chatgpt_ui_network:
    driver: bridge
